drop table if exists sf1geo;
create table "sf1geo" (
-- Record codes
"fileid" text, 
"stusab" text, 
"sumlev" integer, 
"geocomp" integer, 
"chariter" integer, 
"cifsn" text, 
"logrecno" integer, 
-- Geographic aea codes
"region" integer, 
"division" integer, 
"statece" integer, 
"state" integer, 
"county" text, 
"countysc" text, 
"cousub" text, 
"cousubcc" text, 
"cousubsc" text, 
"place" text, 
"placecc" text, 
"placedc" text, 
"placesc" text, 
"tract" text, 
"blkgrp" text, 
"block" text, 
"iuc" text, 
"concit" text, 
"concitcc" text, 
"concitsc" text, 
"aianhh" text, 
"aianhhfp" text, 
"aianhhcc" text, 
"aihhtli" text, 
"aitsce" text, 
"aits" text, 
"aitscc" text, 
"anrc" text, 
"anrccc" text, 
"msacmsa" text, 
"masc" text, 
"cmsa" text, 
"macci" text, 
"pmsa" text, 
"necma" text, 
"necmacci" text, 
"necmasc" text, 
"exi" text, 
"ua" text, 
"uasc" text, 
"uatype" text, 
"ur" text, 
"cd106" text, 
"cd108" text, 
"cd109" text, 
"cd110" text, 
"sldu" text, 
"sldl" text, 
"vtd" text, 
"vtdi" text, 
"zcta3" text, 
"zcta5" text, 
"submcd" text, 
"submcdcc" text, 
-- Area characteristics
"arealand" integer, 
"areawatr" integer, 
"name" text, 
"funcstat" text, 
"gcuni" text, 
"pop100" integer, 
"res" integer, 
"intptlat" integer, 
"intptlon" integer, 
"lsadc" integer, 
"partflag" text, 
-- Special codes
"sdelm" text, 
"sdsec" text, 
"sduni" text, 
"taz" text, 
"uga" text, 
"puma5" text, 
"puma1" text, 
"reserved" text,
primary key (stusab, logrecno)
);

create index idx1 on sf1geo (sumlev)
